site_name: Spike!
site_url: https://joaosilvadev.github.io/spike-docs/
nav:
  - Index: index.md
  - How to Edit Docs: how_to_edit.md
  
  - âš™ï¸ Technical Docs âš™ï¸:
    - Overview: tech_overview.md
    - Networking: tech_networking.md

  - ğŸ•¹ï¸ Game Design Docs ğŸ•¹ï¸:
    - Overview: design_overview.md
    - Gameplay: design_gameplay.md
theme: readthedocs